<?php

return [

    'export' => 'Export',
    'premium_report' => 'Premium Report',
    'generating' => 'Generating document...',
    'download' => 'Download',
    'print' => 'Print',

    // Templates
    'templates' => [
        'project_report' => 'Project Report',
        'activity_report' => 'Activity Report',
        'budget_report' => 'Budget Report',
        'logical_framework' => 'Logical Framework',
        'progress_report' => 'Progress Report',
        'annual_report' => 'Annual Report',
        'proposal' => 'Project Proposal',
    ],

    // Sections
    'sections' => [
        'cover_page' => 'Cover Page',
        'table_of_contents' => 'Table of Contents',
        'executive_summary' => 'Executive Summary',
        'introduction' => 'Introduction',
        'context' => 'Context',
        'objectives' => 'Objectives',
        'expected_results' => 'Expected Results',
        'activities' => 'Activities',
        'budget' => 'Budget',
        'timeline' => 'Timeline',
        'monitoring' => 'Monitoring & Evaluation',
        'conclusion' => 'Conclusion',
        'annexes' => 'Annexes',
    ],

    // Metadata
    'generated_on' => 'Generated on',
    'generated_by' => 'Generated by',
    'page' => 'Page',
    'of' => 'of',
    'confidential' => 'Confidential',

];
